site_name: S5D9 IoT Hacking
theme_dir: theme/material
theme: 'material'
google_analytics: ['UA-86439301-1', 'auto']
repo_url: 'https://github.com/codetricity/s5d9-hacking/'
edit_uri: 'edit/master/docs/'
site_description: 'Community-generated documentation to hack the Renesas S5D9 IoT Fast Prototyping Kit'
site_author: 'Craig Oda and the learn.iotcommunity.io team'

pages: 
- Overview: 
    - 'Board and Dev Tools': 'index.md'
    - 'Hacking Paths': 'hackingpaths.md'
    - 'Requirements': 'requirements.md'
- Data Monitoring:
    - 'Getting Started': 'monitoring/starting.md'
- Data Intelligence:
    - 'Overview and Installation': 'intelligence/overview.md'
    - 'Diagnostics Intelligence Tutorial': 'intelligence/diagnostics.md'
- Develop Your Own Image: 
    - 'Image Dev Tools': 'synergy/custom.md'
    - 'Creating a new Blinky image': 'synergy/blinky.md'
- Design Your Own Board:
    - 'Download design files': 'design/files.md'
    - 'Manufacturing and assembly': 'design/manufacturing.md'
